modLoader="javafml"
loaderVersion="[51,)"
license="All rights reserved"
[[mods]]
modId="luckytntlib"
version="51.0.21.1"
displayName="Lucky TNT Lib"
logoFile="logo.png"
credits="Created, updated and maintained by SlimingHD"
authors="SlimingHD, Fleshcrafter"
description='''
This mod acts as a library for TNT mods usually associated with the word "Lucky".
It allows for quick creation and easy maintenance of TNT mods and is a hard dependency.
'''
[[dependencies.luckytntlib]]
    modId="forge"
    mandatory=true
    versionRange="[51,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.luckytntlib]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.21,1.22)"
    ordering="NONE"
    side="BOTH"
